jenkins:
  systemMessage: "Jenkins Microservicios 2025-2 (Config-as-Code)"
  numExecutors: 2

unclassified:
  location:
    url: "http://jenkins:8080/"

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              id: "sonar-creds"
              username: "admin"
              password: "admin"
              description: "Credenciales SonarQube"

jobs:
  - file: /var/jenkins_home/casc-bundle/jobs/seed.groovy
